bronze:
  base_path: "${BRONZE_BASE_PATH:-samples/bronze}"
  tables:
    - name: "customers"
      partition_key: "signup_date"
    - name: "product_catalog"
      partition_key: "category"
    - name: "orders"
      partition_key: "ingest_dt"
    - name: "order_items"
      partition_key: "ingest_dt"
    - name: "shopping_carts"
      partition_key: "ingest_dt"
    - name: "cart_items"
      partition_key: "ingest_dt"
    - name: "returns"
      partition_key: "ingest_dt"
    - name: "return_items"
      partition_key: "ingest_dt"
