from __future__ import annotations

import os
import tempfile
from pathlib import Path

from src.observability import get_logger
from src.validation.enriched.models import EnrichedTableMetrics

logger = get_logger(__name__)


def generate_markdown_report(
    run_id: str,
    timestamp: str,
    table_metrics: list[EnrichedTableMetrics],
    overall_status: str,
    output_path: str | Path,
) -> None:
    """Generate validation report and write to local or GCS path.

    Args:
        run_id: Run identifier
        timestamp: Report timestamp
        table_metrics: List of table metrics
        overall_status: Overall validation status
        output_path: Report path (local or gs://)
    """
    from src.observability.config import get_config

    status_emoji = {"PASS": "✅", "WARN": "⚠️", "FAIL": "❌"}

    lines = [
        "# Enriched Silver Quality Report",
        "",
        f"**Last Updated:** {timestamp}",
        f"**Run ID:** `{run_id}`",
        f"**Overall Status:** {status_emoji.get(overall_status, '❓')} "
        f"{overall_status}",
        "",
        "## Summary",
        "",
        "| Table | Partition | Value | Rows | Min Rows | Δ vs prior | Status | Notes |",
        "|-------|-----------|-------|------|----------|-----------|--------|-------|",
    ]

    for metrics in table_metrics:
        notes = ", ".join(metrics.notes) if metrics.notes else "-"
        min_rows = metrics.min_rows if metrics.min_rows is not None else "-"
        delta_display = "-"
        if metrics.row_delta_pct is not None:
            delta_display = f"{metrics.row_delta_pct:+.2f}%"
        lines.append(
            f"| {metrics.table} | {metrics.partition_key} | "
            f"{metrics.ingest_dt or '-'} | "
            f"{metrics.row_count:,} | {min_rows} | {delta_display} | "
            f"{status_emoji.get(metrics.status, '❓')} {metrics.status} | {notes} |"
        )

    failing = [m for m in table_metrics if m.status == "FAIL"]
    warning = [m for m in table_metrics if m.status == "WARN"]
    if failing or warning:
        lines.extend(["", "---", "", "## Issues Detected", ""])
        for metrics in failing + warning:
            emoji = status_emoji.get(metrics.status, "❓")
            lines.append(f"### {emoji} {metrics.table}")
            if metrics.ingest_dt:
                lines.append(
                    f"- **Partition:** {metrics.partition_key}={metrics.ingest_dt}"
                )
            lines.append(f"- **Rows:** {metrics.row_count:,}")
            if metrics.min_rows is not None:
                lines.append(f"- **Min Rows:** {metrics.min_rows}")
            if metrics.row_delta_pct is not None:
                lines.append(f"- **Row Delta vs prior:** {metrics.row_delta_pct:+.2f}%")
            if metrics.notes:
                lines.append(f"- **Notes:** {', '.join(metrics.notes)}")
            lines.append("")

    lines.extend(["---", "", "## Schema & Null Rates", ""])
    for metrics in table_metrics:
        lines.append(f"### {metrics.table}")
        if metrics.schema_snapshot:
            lines.append("")
            lines.append("**Schema (column → dtype):**")
            lines.append("")
            lines.append("| Column | Dtype |")
            lines.append("|--------|-------|")
            for col, dtype in metrics.schema_snapshot.items():
                lines.append(f"| {col} | {dtype} |")
        else:
            lines.append("")
            lines.append("- **Schema:** unavailable")
        if metrics.null_rates:
            lines.append("")
            lines.append("**Key Field Null Rates:**")
            lines.append("")
            lines.append("| Column | Null Rate |")
            lines.append("|--------|----------|")
            for col, rate in metrics.null_rates.items():
                lines.append(f"| {col} | {rate:.2%} |")
        else:
            lines.append("")
            lines.append("- **Key Field Null Rates:** unavailable")
        if metrics.sanity_issues:
            lines.append("")
            lines.append(f"**Sanity Issues:** {', '.join(metrics.sanity_issues)}")
        if metrics.semantic_issues:
            lines.append("")
            lines.append(f"**Semantic Issues:** {', '.join(metrics.semantic_issues)}")
        lines.append("")

    lines.extend(
        [
            "---",
            "",
            "## Metadata",
            "",
            "- **Generated by:** `src/validation/enriched/report.py`",
            "- **Report Format Version:** 1.0",
            "",
            "<!-- AUTO-GENERATED - DO NOT EDIT MANUALLY -->",
        ]
    )

    content = "\n".join(lines)

    # Write to local or GCS based on environment
    obs_config = get_config()
    if not obs_config.use_cloud_reports():
        # Local: write to filesystem with atomic replacement
        local_path = Path(output_path)
        local_path.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            delete=False,
            dir=local_path.parent,
            prefix=f".{local_path.name}.",
            suffix=".tmp",
        ) as handle:
            handle.write(content)
            temp_name = handle.name
        os.replace(temp_name, local_path)
        logger.info(f"Wrote Markdown report to: {local_path}")
    else:
        # Dev/Prod: write to GCS
        import fsspec

        fs = fsspec.filesystem("gcs")
        with fs.open(str(output_path), "w") as f:
            f.write(content)
        logger.info(f"Wrote Markdown report to GCS: {output_path}")
